version: '3'
services:
  flask_server:
    build: 
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - backend-network

  nginx_server:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "1935:1935"
    depends_on:
      - flask_server
    networks:
      - app-network

networks:
  backend-network:
    driver: bridge
