FROM tiangolo/nginx-rtmp

COPY nginx.conf /etc/nginx/nginx.conf

# FROM ubuntu:latest

# ENV DEBIAN_FRONTEND=noninteractive

# RUN apt-get update && \
#     apt-get install -y nginx && \
#     apt-get install libnginx-mod-rtmp && \
#     apt-get install libnginx-mod-stream

# COPY nginx.conf /etc/nginx/nginx.conf

# CMD ["nginx", "-g", "daemon off;"]